title: "Jalini M. Rajapakse"
email: "jalinir@bu.edu"
description: >-
  Data Scientist | Bioinformatics Expert | NGS | Oncology  R Shiny | Tableau | Variant Annotation
url: "https://jalini.github.io"
baseurl: ""
repository: "Jalini/jalini.github.io"
github_username: Jalini
logo: "/assets/images/Logo.png"
minimal_mistakes_skin: "sunrise"
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

author:
  name: "Jalini M. Rajapakse"
  avatar: "/assets/images/profile.jpg"  # Add this file manually
  bio: >
    8+ years in clinical diagnostics, oncology data science, and NGS pipelines. Specialist in CLIA-compliant workflows, variant annotation, and bioinformatics automation.
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jalini-manori-rajapakse-181b3129/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Jalini"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:jalinir@bu.edu"

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

markdown: kramdown
kramdown:
  input: GFM

plugins:
- jekyll-include-cache
